logging:
    level:
        com.mousavi007.shop: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop2
    username: roots
    password: 7732760m
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql
