server:
  port: 8080
logging:
    level:
        com.mousavi007.shop: debug
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/shop2
    username: roots
    password: 7732760m
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  thymeleaf:
      mode: LEGACYHTML5

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql
